default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['PG_DB_NAME'] %>
  host: <%= ENV['PG_DB_HOST'] %>
  pool: 5
  username: <%= ENV['PG_USER_NAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

test:
  <<: *default
  database: <%= ENV['PG_TEST_DB_NAME'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['PG_PRODUCTION_DB_NAME'] %>
  host: <%= ENV['PG_DB_HOST'] %>
  pool: 5
  username: <%= ENV['PG_USER_NAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  role: MyRole
